version: "3.9"
services:
  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      PYTHONUNBUFFERED: "1"

  spark:
    build: ./spark
    container_name: spark
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    volumes:
      - ./spark/spark_job.py:/opt/bitnami/spark/app/spark_job.py
    working_dir: /opt/bitnami/spark/app
    command: >
      spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 spark_job.py
